# Generated by Django 4.1.3 on 2022-12-06 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='users_readlater',
            field=models.ManyToManyField(blank=True, related_name='user_readlater', to=settings.AUTH_USER_MODEL),
        ),
    ]
