# Generated by Django 4.1.3 on 2022-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(default='Fox blog', max_length=255, verbose_name='title tag'),
        ),
    ]
