# Generated by Django 4.1.3 on 2022-12-05 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(default='Fox blog', max_length=255, verbose_name='title tag'),
        ),
    ]
