# Generated by Django 4.1.3 on 2022-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_creation_date_blogpost_title_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(default='sport', max_length=255, verbose_name='topic'),
        ),
    ]
