# Generated by Django 4.1.3 on 2022-12-05 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
    ]
